openapi: "3.0.1"
info:
  title: "Quiz Builder API"
  version: "v1.0"
servers:
- url: "http://18.139.172.1:8080"
paths:
  /quizzes/{id}/publish:
    post:
      description: "Publish a quiz"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "404":
          description: "The quiz does not exist."
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuizID"
        "422":
          description: "An empty quiz cannot be published."
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "The user is not the quiz's creator."
          content: {}
      security:
      - Cognito: []
  /users/signup:
    post:
      description: "Sign up a new user"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserSignUp"
          text/plain:
            schema:
              $ref: "#/components/schemas/UserSignUp"
        required: true
      responses:
        "400":
          description: "Invalid request body"
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserID"
  /quizzes/{id}/submissions:
    get:
      description: "List all submissions from a quiz"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "404":
          description: "The quiz does not exist."
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmissionList"
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "The user is not the quiz's creator."
          content: {}
      security:
      - Cognito: []
    post:
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAnswers"
          text/plain:
            schema:
              $ref: "#/components/schemas/UserAnswers"
        required: true
      responses:
        "404":
          description: "The quiz does not exist."
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuestionID"
        "400":
          description: "Invalid request body"
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "A user cannot take his/her own quiz."
          content: {}
      security:
      - Cognito: []
  /quizzes/{id}/questions:
    post:
      description: "Create a question in an unpublished quiz"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Question"
          text/plain:
            schema:
              $ref: "#/components/schemas/Question"
        required: true
      responses:
        "404":
          description: "The quiz does not exist."
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuestionID"
        "422":
          description: "A published quiz cannot be edited."
          content: {}
        "400":
          description: "Invalid request body"
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "The user is not the quiz's creator."
          content: {}
      security:
      - Cognito: []
  /users/confirm:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserConfirmation"
          text/plain:
            schema:
              $ref: "#/components/schemas/UserConfirmation"
        required: true
      responses:
        "400":
          description: "Invalid request body"
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
  /submissions:
    get:
      description: "List all submissions taken by a user"
      responses:
        "401":
          description: "Unauthorized"
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmissionList"
      security:
      - Cognito: []
  /users/auth:
    post:
      description: "Authenticate a user using either a combination of username/password\
        \ or a refresh token"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserAuthentication"
          text/plain:
            schema:
              $ref: "#/components/schemas/UserAuthentication"
        required: true
      responses:
        "400":
          description: "Invalid request body"
          content: {}
        "200":
          description: "An id token is used in http header when sending a request.\
            \ A refresh token is used to get a new id token."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserAuthToken"
  /submissions/{id}:
    get:
      description: "Get a submission's answers"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "404":
          description: "The submission does not exist."
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Submission"
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "The submission does not belong to the user."
          content: {}
      security:
      - Cognito: []
  /quizzes:
    get:
      description: "Get all quizzes created by a user"
      responses:
        "401":
          description: "Unauthorized"
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuizList"
      security:
      - Cognito: []
    post:
      description: "Create a quiz"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuizTitle"
          text/plain:
            schema:
              $ref: "#/components/schemas/QuizTitle"
        required: true
      responses:
        "400":
          description: "Invalid request body"
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuizID"
      security:
      - Cognito: []
  /quizzes/{id}/questions/{qid}:
    put:
      description: "Update a question in an unpublished quiz"
      parameters:
      - name: "qid"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Question"
          text/plain:
            schema:
              $ref: "#/components/schemas/Question"
        required: true
      responses:
        "404":
          description: "The quiz does not exist."
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuestionID"
        "422":
          description: "A published quiz cannot be edited."
          content: {}
        "400":
          description: "Invalid request body"
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "The user is not the quiz's creator."
          content: {}
      security:
      - Cognito: []
    delete:
      description: "Delete a question in an unpublished quiz"
      parameters:
      - name: "qid"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "404":
          description: "The quiz does not exist."
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuestionID"
        "422":
          description: "A published quiz cannot be edited."
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "The user is not the quiz's creator."
          content: {}
      security:
      - Cognito: []
  /quizzes/{id}:
    get:
      description: "Get a quiz's questions and answers"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "404":
          description: "The quiz does not exist."
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quiz"
      security:
      - Cognito: []
    put:
      description: "Update the quiz's title"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QuizTitle"
          text/plain:
            schema:
              $ref: "#/components/schemas/QuizTitle"
        required: true
      responses:
        "404":
          description: "The quiz does not exist."
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuizID"
        "422":
          description: "A published quiz cannot be edited."
          content: {}
        "400":
          description: "Invalid request body"
          content: {}
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "The user is not the quiz's creator."
          content: {}
      security:
      - Cognito: []
    delete:
      description: "Disable a quiz if it is published; Delete a quiz it is unpublished"
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "404":
          description: "The quiz does not exist."
          content: {}
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/QuizID"
        "401":
          description: "Unauthorized"
          content: {}
        "403":
          description: "The user is not the quiz's creator."
          content: {}
      security:
      - Cognito: []
components:
  schemas:
    UserConfirmation:
      title: "User Confirmation"
      required:
      - "confirmation_code"
      - "username"
      type: "object"
      properties:
        username:
          type: "string"
          format: "email"
        confirmation_code:
          type: "string"
    UserAnswers:
      title: "User Answers"
      minItems: 1
      type: "array"
      items:
        type: "array"
        items:
          type: "number"
    UserAuthToken:
      title: "User Auth Token"
      type: "object"
      properties:
        id_token:
          type: "string"
        refresh_token:
          type: "string"
    Submission:
      title: "Submission"
      type: "object"
      properties:
        quiz_title:
          type: "string"
        user_id:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
        total_score:
          type: "number"
        user_answers:
          type: "array"
          items:
            type: "object"
            properties:
              question_text:
                type: "string"
              chosen:
                type: "array"
                items:
                  type: "string"
              score:
                type: "number"
    QuizID:
      title: "Quiz ID"
      type: "object"
      properties:
        quiz_id:
          type: "string"
    UserAuthentication:
      title: "User Authentication"
      required:
      - "auth_type"
      type: "object"
      properties:
        auth_type:
          type: "string"
          enum:
          - "REFRESH_TOKEN"
          - "USER_PASSWORD_AUTH"
        username:
          type: "string"
          format: "email"
        password:
          type: "string"
        refresh_token:
          type: "string"
    SubmissionList:
      title: "Submission List"
      type: "array"
      items:
        type: "object"
        properties:
          submission_id:
            type: "string"
          quiz_title:
            type: "string"
          user_id:
            type: "string"
          timestamp:
            type: "string"
            format: "date-time"
          total_score:
            type: "number"
    Empty:
      title: "Empty Schema"
      type: "object"
    Quiz:
      title: "Quiz"
      type: "object"
      properties:
        title:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
        questions:
          type: "array"
          items:
            type: "object"
            properties:
              question_id:
                type: "string"
              text:
                type: "string"
              is_multiple:
                type: "boolean"
              choices:
                type: "array"
                items:
                  type: "string"
              answers:
                type: "array"
                items:
                  type: "number"
        is_published:
          type: "boolean"
    QuizList:
      title: "Quiz List"
      type: "array"
      items:
        type: "object"
        properties:
          quiz_id:
            type: "string"
          title:
            type: "string"
          timestamp:
            type: "string"
            format: "date-time"
          is_published:
            type: "boolean"
    UserSignUp:
      title: "User Sign-Up"
      required:
      - "password"
      - "username"
      type: "object"
      properties:
        username:
          type: "string"
          format: "email"
        password:
          type: "string"
    QuestionID:
      title: "Question ID"
      type: "object"
      properties:
        question_id:
          type: "string"
    UserID:
      title: "User ID"
      type: "object"
      properties:
        user_id:
          type: "string"
    Question:
      title: "Question"
      required:
      - "answers"
      - "choices"
      - "is_multiple"
      - "text"
      type: "object"
      properties:
        text:
          minLength: 1
          type: "string"
        is_multiple:
          type: "boolean"
        choices:
          maxItems: 5
          minItems: 2
          type: "array"
          items:
            minLength: 1
            type: "string"
        answers:
          maxItems: 5
          minItems: 1
          type: "array"
          items:
            type: "number"
    QuizTitle:
      title: "Quiz Title"
      required:
      - "title"
      type: "object"
      properties:
        title:
          minLength: 1
          type: "string"
  securitySchemes:
    Cognito:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
